sudo: false
cache: bundler
language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - Gemfile
  - gemfiles/Gemfile.activesupport-5.1
  - gemfiles/Gemfile.activesupport-5.2

notifications:
  email: false
